apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-app
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: flask-app
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - echo "Timestamp - $(date '+%Y-%m-%d %H:%M:%S')"
          restartPolicy: OnFailure